version: '2'

services:

  nginx:
   image: nginx:alpine
   ports:
     - '8082:80'
   volumes:
     - './config/nginx.conf:/etc/nginx/nginx.conf:ro'
     - './logs/:/var/log/nginx'
     - 'www:/var/www/html'
   links:
     - 'php:php'
   depends_on:
      - php

  db:
    image: mysql:5.7
    volumes:
      - 'dbdata:/var/lib/mysql'
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_ONETIME_PASSWORD: 'yes'
      MYSQL_DATABASE: test
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mypass

  php:
    image: myimg:latest
    volumes:
      - 'www:/var/www/html'
    links:
      - 'db'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: mysql
      DB_PASSWD: mypass


volumes:
  dbdata:
  www: